#Configurations

[CONFIG]
UPDATE_RATE = 60

[NETWORKING]
HOST_PORT = 8888
HOST_NAME = '192.168.2.1'
CLIENT_NAME = '192.168.2.1'  #192.168.2.2

[THRUSTERS]
FRONT_LEFT_PIN = 26

FRONT_RIGHT_PIN = 21

UP_BACKLEFT_PIN = 6

UP_BACKRIGHT_PIN = 20

UP_FRONTLEFT_PIN = 19

UP_FRONTRIGHT_PIN = 16

[GENERAL]
ARM_PIN = 13
CAMERA_PIN = 25
LEAK_PIN = 5

[PWM]
MAX_PW = 0.0019
MIN_PW = 0.0011

# PINS
# pin | gpio | name
# --------------------------
# 29  | 5    | Leak sensor
# 22  | 25   | Camera servo
# 40  | 21   | ESC
# 38  | 20   | ESC
# 37  | 26   | ESC
# 36  | 16   | ESC
# 35  | 19   | ESC 
# 31  | 6    | ESC
# 33  | 13   | Grabber