#Configurations

[CONFIG]
UPDATE_RATE = 60
MIN_ACTIVATION = 0.12
MAX_PERCENT = 0.8
# as % of range (0-180 deg) per loop
CAMERA_MOVE_SPEED = 0.05
ARM_MOVE_SPEED = 0.05

[NETWORKING]
HOST_PORT = 8888
HOST_NAME = 192.168.2.1
PI_IP = 10.42.0.186

# Pins for the motors
[THRUSTERS]
LEFT = 26

RIGHT = 21

SW = 6

SE = 20

NW = 19

NE = 16

# Pins for the others
[GENERAL]
ARM = 13
# camera servo
CAMERA = 25
LEAK = 5


# in microsec I think
[PWM]
MAX_PW = 1900
MIN_PW = 1100
MID_PW = 1500

# PINS
# pin | gpio | name
# --------------------------
# 29  | 5    | Leak sensor
# 22  | 25   | Camera servo
# 40  | 21   | ESC
# 38  | 20   | ESC
# 37  | 26   | ESC
# 36  | 16   | ESC
# 35  | 19   | ESC 
# 31  | 6    | ESC
# 33  | 13   | Grabber

[SCREEN]
WIDTH = 1600
HEIGHT = 1050
BACKGROUND_COLOR = (31, 31, 31)

[CAMERA1]
WIDTH = 854
HEIGHT = 480

# TODO: Add more settings regarding controller layout